### ISSUE TITLE
Some apex template files are missing in the repository

### ISSUE THREAD

**Issue by DanielWenz** [jkvetina/CORE#1]
Hello,

based on the apex install.sql the follwoing resources are missing in the repository:

@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/standard_q.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/navigation_bar_q.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql

Would you mind to add these?

Thank you

**Comment by jkvetina** [comment]
It is a standard export from APEX, just unzipped into folders. I can send you the .sql file if you connect with me on LinkedIn and it should be easier to import. Or you can try to pack the f770 folder s a .zip and import that in APEX.

**Comment by DanielWenz** [comment]
Hi,

Thank you for your response I accpeted you on LinkedIn

Daniel Wenz

**Comment by maheshdmtech** [comment]
Thanks Jan,
I did tried by creating a zip file of folder f770 but it fails stating above mentioned files are missing. this is the error "Unable to find the file. f770/application/shared_components/user_interface/templates/page/left_side_column.sql" would it be possible for you to upload fresh complete app export file i.e. f770.sql 

Thanks. 
good day.

**Comment by jkvetina** [comment]
Added to the repository.
https://github.com/jkvetina/CORE/blob/main/apex/f770.sql
